### ISSUE TITLE
[BUG] Ao abrir janelas pinnadas no taskmanager, outra janela é criada em vez de sobrepor ao pin

### ISSUE THREAD

**Issue by arthurcaccavo** [biglinux/biglinux-webapps#121]
Para reproduzir:
- Selecione um browser baseado em chromium para abrir o webapp
- Abra uma janela do webapp, clique com botão direito no Task Manager e selecione "pin to Task Manager"
- Feche a janela e abra novamente
- Haverão duas instâncias do webapp
![image](https://github.com/user-attachments/assets/5d20577f-3f6d-49ad-9904-38551f899578)
- Entretanto, ao mover a janela entre monitores ou entre atividades o problema é resolvido

Caso eu consiga fornecer mais logs para ajudar no entendimento do problema basta me informar q ficarei grato em ajudar!

Muito obrigado pelo empenho nesse sistema maravilhoso!

**Comment by arthurcaccavo** [comment]
Relacionado:
https://bugs.kde.org/show_bug.cgi?id=358277
https://chromium-review.googlesource.com/c/chromium/src/+/3383817

**Comment by eltonfabricio10** [comment]
Ja esta sendo resolvido na próxima versão, aguarde o novo lançamento

**Comment by arthurcaccavo** [comment]
Corrigido na versão atual!
