### ISSUE TITLE
[request] Brave-bin mudou de local

### ISSUE THREAD

**Issue by omauriciofala** [biglinux/biglinux-webapps#24]
Ontem ao atualizar o Arch, me deparei com a situação de que ele mudou de diretório.

Antes era **/usr/lib/brave-bin/brave**

Agora é **/opt/brave-bin/brave**

Não sei se foi apenas no Arch, ou quando atualizar no Manjaro pode vir a acontecer.

**Comment by eltonfabricio10** [comment]
Esse pacote é do AUR... Então se muda pra um, muda pra todos...

**Comment by eltonfabricio10** [comment]
corrigido em #25
