### ISSUE TITLE
[Feature Request] Browser classification

### ISSUE THREAD

**Issue by shadichy** [biglinux/biglinux-webapps#41]
This is what I was trying to perform back then (my fork). It makes browser support a lot easier than adding each one manually.

My idea is to divide web browsers into 3 main groups (including their official Snap and Flatpak versions):

- Chromium (blink) based includes:

     Google Chrome (stable/dev/unstable), 
     Chromium (stable/dev/unstable), 
     Ungoogled Chromium
     Brave(stable/nightly), 
     Vivaldi (stable/snapshot),
     Microsoft Edge (stable/dev/beta),
     Iron (Chrome precursor),
     Yandex Browser (stable/beta),
     Naver Whale (for Korean users),
     Iridium Browser,
     Decentr Browser (stable/beta),
     Thorium Browser,
     Flashpeak Slimjet (stable/beta),
     Electron (5 to latest) and some other NodeJS-based browsers that are capable of running web apps,
     Firefox PWA (firefox-pwa, yes, it's not moz-gecko),
     Midori (yes, it switched from WebKit-GTK based to Electron based)
     Opera (if they tend to bring back web app feature), 
     ...

- Quantum/Gecko (moz) based (waterfox and other moz-gecko based do count) includes:

     Firefox (all ver),
     LibreWolf (all ver),
     FireDragon (Firefox fork of Garuda Linux),
     Waterfox (all ver),
     SpiderMonkey (all ver),
     Falkon,
     Tor,
     Dot
     SeaMonkey,
     Ghostery,
     Not recommended: Avant, Cliqz, PaleMoon, basilisk, K-meleon, IceDragon, IceCat;
     ...

- WebKit-GTK based includes:

     Epiphany,
     Tangram,
     ...

Considering Qt web browsers are not  in a distinct group, because most of them don't support PWAs

**Comment by eltonfabricio10** [comment]
Ok, but why all this browser if at the end of the day users are only going to use Google Chrome?

**Comment by shadichy** [comment]
> Ok, but why all this browser if at the end of the day users are only going to use Google Chrome?

Just let them use it.
I don't know if there is any misunderstanding here, but if you don't get it, let me explain it again:

> This is what I was trying to perform back then (my fork). It makes browser support a lot easier than adding each one manually.
> 
> My idea is to divide web browsers into 3 main groups (including their official Snap and Flatpak versions):
> - Chromium (blink) based
> - Quantum/Gecko (moz) based (waterfox and other moz-gecko based do count)
> - WebKit-GTK based

TBH, it looks like this JSON: 
```json
{
  "groups": [
    {
      "groupname": "chromium",
      "browsers": [
        {
          "name": "Google Chrome",
          "path": "/opt/google/chrome/chrome",
          "icon": "/path/to/icon.svg_or_png"
        },
        {
          "name": "Google Chrome (Snap)",
          "path": "/var/lib/snapd/snap/bin/chrome",
          "icon": "/path/to/icon.svg_or_png"
        },
        {
          "name": "Microsoft Edge Dev",
          "path": "/opt/google/microsoft/msedge-dev/msedge",
          "icon": "/path/to/icon.svg_or_png"
        },
        {
          "name": "Electron 24",
          "path": "/usr/bin/electron24",
          "icon": "/path/to/icon.svg_or_png"
        },
        ...and so on
      ]
    },
    {
      "groupname": "moz",
      "browsers": [
        {
          "name": "Firefox",
          "path": "/usr/bin/firefox",
          "icon": "/path/to/icon.svg_or_png"
        },
        {
          "name": "FireDragon",
          "path": "/usr/bin/firedragon",
          "icon": "/path/to/icon.svg_or_png"
        },
        {
          "name": "LibreWolf",
          "path": "/usr/bin/librewolf",
          "icon": "/path/to/icon.svg_or_png"
        },
        ...and so on
      ]
    },
    {
      "groupname": "webkitgtk",
      "browsers": [...similar to above example]
    }
  ]
}
```

**Comment by solos-be** [comment]
> Ok, but why all this browser if at the end of the day users are only going to use Google Chrome?

but Google is faltering more and more , increasing also their paid-for results  :(
so I switch more friends to ecosia.org non-Google and non-USA based

**Comment by eltonfabricio10** [comment]
Wait for release of new version for new suggestions
