### ISSUE TITLE
[Adição] Controle pela linha de comando

### ISSUE THREAD

**Issue by guiga-zalu** [biglinux/biglinux-webapps#5]
Tenho interesse em utilizar a ferramenta "`biglinux-webapps`" como uma ferramenta de linha de comando, com suporte _"CRUD"_ (criar, ler, editar e apagar) completo.

Creio que para adicionar estas funcionalidades, ter uma _"issue"_ como direcionamento de desenvolvimento é um recurso útil.

Para realizar estas adições, imagino necessário:

1. Transformar `biglinux-webapps` em um comando mestre, que:
   - Ao ser invocado sem argumentos, mantém as funcionalidades padrão, como invocar a interface via `big-bash-view`.
   - Ao ser invocado com um comando, executa o comando sem invocar a interface.
     Exemplos de comandos:
     - `biglinux-webapps import <arquivo.json>` (capaz de atualizar ao sobrescrever o anterior)
     - `biglinux-webapps export <webapp> <arquivo.json>`
     - `biglinux-webapps enable <webapp>`
     - `biglinux-webapps disable <webapp>`
     - `biglinux-webapps change-browser <browser>`
1. Documentar as funções, como o executor `biglinux-webapp` e os outros: `change_browser.sh`, `change_icon.sh`, `enable-disable.sh`, `webapp-install.sh` e `webapp-remove.sh`, com comando `-h` ou `--help` que apenas descreve a funcionalidade.

**Comment by eltonfabricio10** [comment]
Qual o motivo de usar na linha de comando?

**Comment by eltonfabricio10** [comment]
Recurso será adicionado via PR se houver
