### ISSUE TITLE
[Feature Request] Extension support

### ISSUE THREAD

**Issue by Terkyz** [biglinux/biglinux-webapps#8]
Quer eu use Brave ou Firefox, as extensões são ferramentas extremamente úteis que podem tornar a experiência de navegação mais personalizada, e acredito que isto pode ser feito de duas maneiras:

1. Deve haver um menu global de "extensões" (que se aplica a qualquer perfil, Brave, Firefox ou perfis separados) e que se assemelha a uma típica loja de aplicativos, mas com extensões que cumprem uma função específica, como modo escuro, adblocker, tradutor, etc, e que estas são instaladas ou desinstaladas com um simples clique do usuário, sendo um simples script que instala estas extensões "recomendadas".

2. Um botão/caixa na janela de criação/gestão de um webapp que tem a opção "extensões" e que abre automaticamente a loja de extensões do navegador definido para que o usuário escolha quais usar em seu webapp, e uma vez concluído o processo, estas estarão em seu webapp.

**Comment by eltonfabricio10** [comment]
Da forma que geramos os webapps não tem suporte a extensões
